### ISSUE TITLE
cookie-domain should be a list if it needs to cover all whitelist-domains

### ISSUE THREAD

**Issue by r0fls** [pusher/oauth2_proxy#115]
I am trying to follow: https://thenewstack.io/single-sign-on-for-kubernetes-dashboard-experience/

And I'm encountering a redirect loop from: 
k8s dashboard -> oauth2-proxy -> dex -> upstream OIDC provider -> dex -> upstream OIDC provider ...

I searched some old issues and it seems it could be the cookie-domain arguement needs to be set. However the `whitelist-domain` argument is currently set to a list of domains for us (since they don't all have the same TLD, e.g. *.foo.com and *.bar.com).

If the `cookie-domain` argument is required, it should also accept a list, like `whitelist-domain` does.

**Comment by JoelSpeed** [comment]
Hey @r0fls, I'm just trying to think about how having multiple possible cookie domains would work. As far as I'm aware you can only set one domain for a cookie to be valid for as per limitations of the general web protocols. Perhaps we could have something that guesses the right cookie domain to set? The problem here would be that the two cookies would not be synchronised and you therefore would not be able to handle refreshing.

The design of and reason for `whitelist-domain` taking multiple arguments was so that you could specify a list of `a.example.com, b.example.com, etc.` that would be a specific list of domains under *one* TLD rather than just allowing any domain under said TLD. The OAuth2 Proxy wasn't really designed to protect more than one domain at a time and even the whitelist domain is a bit of a hack. 

Is there any reason you don't want to run one OAuth2 Proxy per TLD?

**Comment by r0fls** [comment]
Thanks @JoelSpeed for thinking about this. The main reason I didn't think to run separate oauth2-proxy's per cluster is that we only have one instance of dex deployed, and I was coupling oauth2-proxy with the dex deployment.

The second reason though, is I'm not sure that will work. We have dex and oauth2-proxy on one domain, let's say *.foo.com, and the k8s cluster on another, let's say k8s.bar.com. When I try setting the cookie-domain to k8s.bar.com, I get redirected to the oauth2 proxy after the oauth2 workflow with dex, and see the message: 403 named cookie not present. However, when I set it to .foo.com, it gets stuck in the redirect loop.

**Comment by ploxiln** [comment]
a browser will not allow you to set a cookie for both `*.foo.com` and `k8s.bar.com` from the same page/service - if the auth page is from `auth.foo.com` your only options are 1) domain unspecified, cookie only applies to auth.foo.com 2) domain=.foo.com, cookie applies to *.foo.com 3) domain=foo.com, cookie applies to foo.com and *.foo.com

this is why a list of cookie domains does not make sense. you can only really choose between TLD or subdomain

there is a way to get what you want, with redirects between domains ... for that functionality consider https://github.com/buzzfeed/sso

**Comment by r0fls** [comment]
OK, so just so I understand my options, would this work if oauth2-proxy were hosted on the same TLD as the kubernetes clusters, e.g. `oauth2.bar.com` in my example? Or would dex also need to be hosted from that domain?

**Comment by ploxiln** [comment]
yes, you can have oauth2-proxy on the same TLD as the application it is protecting, and the provider (dex) on some other domain - that works

**Comment by r0fls** [comment]
Thanks for the help!
