### ISSUE TITLE
Question: Is it possible to specify the post-authorization URL with /oauth2/start?

### ISSUE THREAD

**Issue by Ghazgkull** [pusher/oauth2_proxy#125]
I'm using oauth2_proxy with the nginx auth_request module and OIDC. When the proxy reports that a request is not authorized and nginx redirects to /oauth2/start, I would like to pass along a final "post-authorization" URL that the browser should end up at after the OIDC dance completes.

Is this possible? Is there some header I can set when nginx forwards the request to /oauth2/start? (If so, I'd be curious whether I need to pass a full URL or if an absolute path would do.)

**Comment by ploxiln** [comment]
If you redirect to `/oauth2/sign_in` instead of `/oauth2/start`, then you can set the header `X-Auth-Request-Redirect`, in the example nginx config this is done with:

```
proxy_set_header X-Auth-Request-Redirect $request_uri;
```

If you really want to use `/oauth2/start` then you can add an rd parameter, sort of like `/oauth2/start?rd=$request_uri`, but you may need to url-encode that request_uri, and I think there's no way to do that without a non-core nginx module. For simple URIs it might work.
