### ISSUE TITLE
How to use tokens as bearer tokens for API calls from a SPA?

### ISSUE THREAD

**Issue by dmeenhuis** [pusher/oauth2_proxy#199]
I have a similar use-case as #184  where I also have a SPA (React application, which is served from a Docker image running nginx and just serves static files) and a separate API. Both are deployed as individual services in Kubernetes with nginx as an ingress controller in front of them. The site has oauth2_proxy deployed as a sidecar container and handles authentication against Azure AD.

This setup works just fine for the site and with the proper config I am able to get both the access and ID tokens set as cookies, but they are encrypted. 

I would like to use the tokens from oauth2_proxy in my SPA and pass them as a bearer token in the authorization header to the API. In the current setup that doesn't work straight away since the tokens are encrypted, so the API would have no way to use them unless I implement decryption there.

I also looked at the additional configuration options that allow the unencrypted tokens to be passed through as authorization headers to the upstream server. While that works, it would only pass them to the nginx Docker container that serves my SPA and I still would have no way to actuallly get them to the browser so I can use them.

What would be the best way to go about this? I thought about configuring the nginx server in such a way that it sets an additional cookie containing the unencrypted token from the authorization header. This would actually work, but I'm not sure if it's ideal security-wise.

**Comment by sharif9876** [comment]
Does your API have the capability to use JWT tokens that you get from Azure AD?

**Comment by PaulCharlton** [comment]
@dmeenhuis been there and done that - re: `I would like to use the tokens from oauth2_proxy in my SPA and pass them as a bearer token in the authorization header to the API`. If you put the API behind the oauth2 proxy also, you can configure the oauth2 proxy to provide the unencrypted JWT auth token to the API upstream container.  Likewise, your upstream api container can put the JWT token back into a response header which is then available to the JS Application in the browser via https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getAllResponseHeaders.  This works to a point, and breaks if your flow needs a token refresh in the middle of the API call since the OAuth2 proxy is not sharing the refresh token with anybody and the AJAX XHR library can not intercept the 302 redirect, which is generally fatal if the refresh requires any sort of user interaction due to OAuth provider policy.   As for security, what are the risks associated with the browser receiving the unencrypted JWT token? [insert token hijacking scenarios here]

**Comment by sneko** [comment]
Hi @PaulCharlton,

In my case I use both the frontend and API behind the OAuth2proxy process, but even with all settings set my API never receives any header.

That's so strange... the login flow is working normally. You can find more detrails here https://github.com/pusher/oauth2_proxy/issues/337#issuecomment-568146049

**Comment by leopku** [comment]
Hi @sneko ,

I meet same confusion. 

Did you have solutions?
