### ISSUE TITLE
Redirect to Another Domain

### ISSUE THREAD

**Issue by Queuecumber** [pusher/oauth2_proxy#216]
Not sure if I'm missing something here, this is maybe related to #10 or #24 

We have a lot of subdomains that need authentication, so instead of having an auth endpoint for each we we have a single https://auth.example.com endpoint which is oauth2-proxy and sets the cookie for domain example.com

When we do that using the example code, the user is redirected to https://auth.example.com/whatever instead of https://service.example.com/whatever

Is there a way to include the domain in the redirect parameter?

**Comment by JoelSpeed** [comment]
Hi @Queuecumber, there is indeed, since you have OAuth2 Proxy centrally, I'm assuming you have nginx set up in front of each of your service endpoints, redirecting to oauth2 when you need to authenticate?

In that case, you can set the `rd=https://$host$uri` query string parameter in nginx config for the `signin-url` (this is the annotation name for nginx-ingress at least) or the `error_page 401` directive in raw nginx config

Finally, you'll need to set the `--whitelist-domains=.example.com` and `--cookie-domain=.example.com` too. Whitelist allows any subdomain of `example.com` to be redirected to in the `rd` parameter, and the `cookie-domain` ensures that the cookie is valid for all of the domains you're authenticating

**Comment by Queuecumber** [comment]
Confirmed this works perfectly, thanks a lot

**Comment by scottnuma** [comment]
A note for others who reference this, the [documentation on configuration](https://pusher.github.io/oauth2_proxy/configuration) has `whitelist-domain` instead of `whitelist-domains`

**Comment by Just-Insane** [comment]
When trying to get this working, I am being redirected to https://oauth.domain.com, instead of https://myapp.domain.com.

I have the following Oauth2_Proxy config:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak
            - --email-domain=corp.domain.com
            - --email-domain=domain.com
            - --pass-basic-auth=false
            - --pass-access-token=true
            - --set-authorization-header=true
            - --pass-authorization-header=true
            - --http-address=0.0.0.0:4180
            - --login-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/auth
            - --redeem-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/token
            - --validate-url=https://auth.domain.com/auth/realms/realm/protocol/openid-connect/userinfo
            - --cookie-expire=4h0m0s
            - --whitelist-domain=".corp.domain.com",".domain.com"
            - --cookie-domain=".corp.domain.com"
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: rancher-demo
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: <secret>
            # docker run -ti --rm python:3-alpine python -c 'import secrets,base64; print(base64.b64encode(base64.b64encode(secrets.token_bytes(16))));'
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: <secret>
          image: quay.io/pusher/oauth2_proxy:v4.1.0
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
```

I am using Istio-IngressGateway as my ingress gateway, and have an envoy filter with the following code (this is the only way to get oauth working in Istio, as it only validates JWTs):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          portNumber: 443
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          config:
            inlineCode: |
              oauth_host = "oauth.corp.domain.com"

              function starts_with(str, start)
                return str:sub(1, #start) == start
              end

              function login (request_handle)
                -- This did not seem to be working, so I tried hardcoding the domain
                -- local request_url = "https://"..request_handle:headers():get(":authority")..request_handle:headers():get(":path")
                local request_url = "https://rancher-demo.corp.domain.com"
                local redirect_url = "https://"..oauth_host.."/oauth2/start?rd="..request_url
                headers = {
                    [":status"] = 302,
                    ["location"] = redirect_url
                }
                request_handle:respond(headers, "")
              end

              function envoy_on_request(request_handle)

                cookie = request_handle:headers():get("Cookie")
                if cookie == nil then
                  -- request_handle:logWarn("login")
                  login(request_handle)
                  return
                end
                -- request_handle:logWarn("validating token against /ouath2/auth")
                local headers, body = request_handle:httpCall(
                    "outbound|443||"..oauth_host,
                    {
                      [":method"] = "GET",
                      [":path"] = "/oauth2/auth",
                      [":authority"] = oauth_host,
                      ["Cookie"] = cookie
                    },
                    nil,
                    5000)
                local status
                for header, value in pairs(headers) do
                  if header == ":status" then
                      status = value
                  end
                end

                -- request_handle:logWarn("token validation status:"..status)
                if status ~= "202" then
                  -- request_handle:logWarn("Not validated")
                  login(request_handle)
                  return
                end
              end
```
The envoy filter above was copied from [https://github.com/istio/istio/issues/14969#issuecomment-573445692](https://github.com/istio/istio/issues/14969#issuecomment-573445692) with some modifications to remove the base_host.

Even with the redirect_url being hardcoded the way that it is, the url from keycloak has the oauth.corp.domain.com/oauth2/callback redirect_url, and from there I am redirected to oauth.corp.domain.com, not rancher-demo.corp.domain.com.

I saw that there were some problems with --skip-provider-button option, so I have removed that.

The issue seems similar to https://github.com/pusher/oauth2_proxy/issues/328 as well as https://github.com/pusher/oauth2_proxy/issues/125

**Comment by JoelSpeed** [comment]
@Just-Insane please open a new issue if you are having problems, please try not to post on closed issues

**Comment by leonardbiofi** [comment]
> Hi [@Queuecumber](https://github.com/Queuecumber), there is indeed, since you have OAuth2 Proxy centrally, I'm assuming you have nginx set up in front of each of your service endpoints, redirecting to oauth2 when you need to authenticate?
> 
> In that case, you can set the `rd=https://$host$uri` query string parameter in nginx config for the `signin-url` (this is the annotation name for nginx-ingress at least) or the `error_page 401` directive in raw nginx config
> 
> Finally, you'll need to set the `--whitelist-domains=.example.com` and `--cookie-domain=.example.com` too. Whitelist allows any subdomain of `example.com` to be redirected to in the `rd` parameter, and the `cookie-domain` ensures that the cookie is valid for all of the domains you're authenticating



HI, 

I am having exactly the same case but instaed of NGINX I do have the `envoy` proxy in front. 

Everything works as a charm excepts that once the user is authenticated it redirects to the auth.mydomain domain... 

whereas the original request was made on docs.mydomain.
Would you have an idea about this @JoelSpeed
