### ISSUE TITLE
Callback URI redirects to signin URI

### ISSUE THREAD

**Issue by jheidbrink** [pusher/oauth2_proxy#328]
We have an nginx-ingress that uses oauth2_proxy's `/oauth2/auth` endpoint to authenticate requests. If that endpoint replies with 401, it redirects the user to the `/oauth2/sign_in?rd=<original_url>` endpoint, where `<original_url>` is the URL that the user originally requested.

## Expected Behavior

After signing in, the `/oauth2/callback` endpoint should redirect the user to the URL that was originally requested.

## Current Behavior

After signing in, the `/oauth2/callback` endpoint redirects the user to `/oauth2/sign_in?rd=<original_url>` endpoint.

## Possible Solution

In the `SignIn` function, `getRedirect` is called to obtain the redirect from the `rd` parameter (or from the `X-Auth-Request-Redirect` request header).

The `SignIn` function calls `SignInPage`, but does not pass on the obtained value for `redirect`. Instead, the `SignInPage` has its own logic to determine the redirect (I guess it becomes `/oauth2/sign_in?rd=<original_url>`, at least that's what the user eventually gets redirected to).

I think if the `SignInPage` would accept a `redirect` parameter, and the `SignIn` function would pass the `redirect` variable on to `SignInPage`, this would lead to the desired behaviour.

## Your Environment

- Version used: 4.0.0

**Comment by foot** [comment]
We also ran into this while trying to show the sign in page rather than immediately redirecting to github in combination w/ nginx-ingress. We replaced the [recommended annotations from nginx-ingress](https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/auth/oauth-external-auth)

```diff
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
-   nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
+   nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/sign_in?rd=$escaped_request_uri"
```

But we also end up in the loop you describe. Your suggested changes make sense to me! 👍 

As a workaround reading `?rd=` and chucking it in `X-Auth-Request-Redirect` seems to work. As an annotation on the public `/oauth2/` ingress object:

```yaml
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set_unescape_uri $rd $arg_rd;
      proxy_set_header X-Auth-Request-Redirect $rd;
```

**Comment by JoelSpeed** [comment]
I'm aware there is some discrepancy between the different routes for authentication at the moment, eg, as @foot says, you can use a header rather than the query value with `sign_in`. 

@jheidbrink Your proposed solution sounds good, if it's possible to align the redirect logic for both endpoints, that would be awesome, does anyone have time to put a PR together for this?

**Comment by ti-mo** [comment]
@JoelSpeed I also ran into this, and it looked like a fairly straightforward change. #405
Let me know what you think!

**Comment by JoelSpeed** [comment]
#405 should fix this, closing for now, we can reopen if the issue persists
