### ISSUE TITLE
I can no longer run linux-amd64 prebuild binary on Alpine.

### ISSUE THREAD

**Issue by bulzipke** [pusher/oauth2_proxy#329]
## Expected Behavior
./oauth2_proxy --help

> Usage of oauth2_proxy:
>   -acr-values string
>         acr values string:  optional, used by login.gov (default "http://idmanagement.gov/ns/assurance/loa/1")
>   -approval-prompt string
> blah blah

## Current Behavior
./oauth2_proxy --help
> /bin/sh: ./oauth2_proxy: not found

## Possible Solution
Binary in the docker(quay.io/pusher/oauth2_proxy) work well
-> oauth2_proxy v4.1.0-1-gef8b7b5 (built with go1.13.5)
Previous binary (https://github.com/pusher/oauth2_proxy/releases/download/v4.0.0/oauth2_proxy-v4.0.0.linux-amd64.go1.12.1.tar.gz) work well 
-> oauth2_proxy v4.0.0 (built with go1.12.7)

## Steps to Reproduce (for bugs)

1.   FROM alpine:latest (docker)
2.   curl -o file.tar.gz -L https://github.com/pusher/oauth2_proxy/releases/download/v4.1.0/oauth2_proxy-v4.1.0.linux-amd64.go1.13.5.tar.gz
3.   tar xfz file.tar.gz
4.   ./oauth2_proxy-v4.1.0.linux-amd64.go1.13.5/oauth2_proxy

## Your Environment

- Version used: oauth2_proxy-v4.1.0.freebsd-amd64.go1.13.5.tar.gz

**Comment by steakunderscore** [comment]
Just confirmed this issue. Using v4.0.0 works as expected, but v4.1.0 does not.

**Comment by JoelSpeed** [comment]
Have we changed anything about the build process? This sounds like it's going to be some kind of linking issue due to CGO I suspect

We built the binaries using a `make release` target on a macbook, but a different macbook to the previous release, I wonder if there's something strange going on with the dependencies for this

Perhaps we should get all the builds to run inside docker so we can pin dependencies and it doesn't depend on who's machine built it 😅 

I wonder if adding `CGO_ENABLED=0` to the [dist.sh](https://github.com/pusher/oauth2_proxy/blob/master/dist.sh) for building the binaries would make a difference?

**Comment by tomelliff** [comment]
Yep, just ran into this and looks like a CGO issue:
```
/ # apk --no-cache add binutils
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/3) Installing libgcc (9.2.0-r3)
(2/3) Installing libstdc++ (9.2.0-r3)
(3/3) Installing binutils (2.33.1-r0)
Executing busybox-1.31.1-r9.trigger
OK: 29 MiB in 38 packages
/ # readelf -l /bin/oauth2_proxy | grep "program interpreter"
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
/ # ls -la /lib64/ld-linux-x86-64.so.2
ls: /lib64/ld-linux-x86-64.so.2: No such file or directory
```
