### ISSUE TITLE
Is there a way to only allow users with 2FA-activated to log in?

### ISSUE THREAD

**Issue by olegblecher** [pusher/oauth2_proxy#359]
Hi there.

I have a web-based application with sensitive data, and for this reason I only want users that have 2FA activated to be able to log on.

Is there a way to force some kind of a check that does not let a user log on unless they've activated 2FA?

## Your Environment

Debian 9, Nginx.

- Version used: oauth2_proxy v2.2.0

**Comment by JoelSpeed** [comment]
Unfortunately, as far as I am aware, this is not something that we can identify when performing an authentication flow. Normally this kind of information is not accessible with the profile information provided.

That said, some Identity Providers, hypothetically may offer this information as part of the Profile URL data, but this would be on a per provider basis and I'm not aware of any that actually do it

Perhaps 2FA can be enforced for users at the identity provider level rather than the oauth proxy level?

**Comment by olegblecher** [comment]
@JoelSpeed this does answer my question - whether this is possible or not.

A good work-around was to create a user group called "2FA users" (on Google), force 2FA on its members, and only allow members of that group to log in to my application. The oauth2_proxy documentation covers how to do that, and I'm very grateful for that :)

So I am closing this issue.

More info can be found here: https://github.com/pusher/oauth2_proxy/blob/master/docs/2_auth.md#restrict-auth-to-specific-google-groups-on-your-domain-optional
