### ISSUE TITLE
Docs do not include the session.md information

### ISSUE THREAD

**Issue by holyjak** [pusher/oauth2_proxy#384]
The doc site at https://pusher.github.io/oauth2_proxy/ should also include page with the content of [docs/configuration/session.md](https://github.com/pusher/oauth2_proxy/blob/master/docs/configuration/sessions.md) so that people can learn about the cookie vs Redis storage. Thank you!

**Comment by JoelSpeed** [comment]
This page is already accessible, it just hides until you click on configuration https://pusher.github.io/oauth2_proxy/configuration/sessions

**Comment by holyjak** [comment]
I see. It hides really, really well. Perhaps put the link at least at the
beginning of the page and not the very end?

**Comment by JoelSpeed** [comment]
It is also listed in the sidebar with the rest of the pages once you've clicked on configuration.

I had thought it was also linked when you read the option for session store type but it is not. Would be good to add a link in the table so that people read more if they see the `--session-store-type` description

**Comment by holyjak** [comment]
Thank you!
