### ISSUE TITLE
G-Suite Groups with users outside domain unable to be authorized

### ISSUE THREAD

**Issue by KSchmeeds** [pusher/oauth2_proxy#95]
## Expected Behavior

All members inside the specified G-Suite group should be able to authenticate.

## Current Behavior

Users in the group belonging to the same G-Suite organization are able to authenticate, but users outside the domain or regular gmail users can not.

## Steps to Reproduce (for bugs)

1.  Setup Oauth2_Proxy with Google group authorization as described in the readme.
2.  Add a user to the group with a G-Suite account in the same domain as the group oauth2_proxy is checking
3.  Add users not from inside your organization, such as a regular Gmail user
4.  Try to access the protected services behind oauth_proxy using both accounts

## Context

/var/log/syslog output

04:31:13 google.go:189: error fetching user: googleapi: Error 404: Resource Not Found: userKey, notFound
04:31:13 oauthproxy.go:754: 127.0.0.1:50424 ("192.168.0.96") Permission Denied: "user@gmail.com" is unauthorized
04:31:13 oauthproxy.go:498: ErrorPage 403 Permission Denied Invalid Account

## Your Environment

Ubuntu 18.04 with nginx 1.14.0

- Version used:
3.1.0

**Comment by JoelSpeed** [comment]
I believe this is a limitation on the Google API. 

The way this works is by using a Google service account within your GSuite. You give this service account two permissions, one to read the group's within your organisation and one to read the users within your org.

The problem here is that the service account doesn't have permission to read users outside of your org and throws this error.

If I remember correctly the reason we have to look up users is to find their ID as when you retrieve a Group, it doesn't contain user emails but rather the user IDs as members. 

If I'm wrong on that (or things have changed) then we may be able to rewrite the group checking mechanism in `providers/google.go` and fix this issue.

Will need some digging into the Google Admin API documentation!

**Comment by KSchmeeds** [comment]
Hi Joel,

I tried out the the idea of the API being the limiting factor, so I checked the group membership using [GAM with the print group-members](https://github.com/jay0lee/GAM/wiki/GAM3DirectoryCommands#print-group-members).  It did return all users in the group, even those with an @gmail.com address.

My knowledge with using the API is rather limited, but I think we just need oauth2_proxy to use a different request with a different API scope.

**Comment by JoelSpeed** [comment]
Ok that sounds like good news to me, we may be able to fix this!

Do you happen to have an example of the API request you made and a maybe even a sample response? Might help us to find the right implementation from the SDK

**Comment by KSchmeeds** [comment]
I can't find exactly which API call GAM uses when doing the "gam print group-members" command, but I think it might be using [this one](https://developers.google.com/admin-sdk/directory/v1/reference/members/list).  

[It looks like they also have this one](https://developers.google.com/admin-sdk/directory/v1/reference/members/hasMember), that returns a true/false if the user is a member of the group.  This may be an easier one to implement.

**Comment by cemo** [comment]
@KSchmeeds hasMember seems not working for outside of the domain but `get` is working. See: 

https://developers.google.com/admin-sdk/directory/v1/reference/members/get?apix=true
